version: '3.9'
services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  zipkin:
    image: 'openzipkin/zipkin:3.4'
    ports:
      - '9411:9411'