movom:
  api-version: /api/v1/${spring.application.name}

spring:
  application:
    name: movom
  output:
    ansi:
      enabled: always
  profiles:
    active: @mainActiveProfile@
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/movom_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/migration/{vendor}/@mainActiveProfile@
  jackson:
    serialization:
      indent-output: true

management:
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true

logging:
  level:
    tn:
      movom:
        app: TRACE