movom:
  api-version: /${spring.application.name}/api/v1
  security:
    is-enabled: false
  external-apis:
    - name: restfulcountries
      base-url: https://restfulcountries.com/api/v1
      requires-authz: true
      access-token: ${RESTFULCOUNTRIES_ACCESS_TOKEN}

spring:
  application:
    name: movom
  output:
    ansi:
      enabled: always
  profiles:
    active: @mainActiveProfile@
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/movom_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  flyway:
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/migration/{vendor}/@mainActiveProfile@
  jackson:
    serialization:
      indent-output: true
  docker:
    compose:
      enabled: false
  config:
    import:
      - optional:import/secrets/restfulcountries-secrets.yml
      - optional:import/conf/actuator-info.yml

management:
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    tn:
      movom:
        app: TRACE
    org:
      springframework:
        web: DEBUG
        security: DEBUG

---

spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: optional:import/conf/k8s-config.yml