spring:
  application:
    name: movom
  output:
    ansi:
      enabled: always
  profiles:
    active: @mainActiveProfile@
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/movom_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/migration/{vendor}/@mainActiveProfile@

logging:
  level:
    tn:
      movom:
        app: TRACE